spring.datasource.url=jdbc:postgresql://coinflow_db:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres


testing.app.secret=f8faf1417e1ac61e5ecaae12dc02bc7cd32ba5fc64c9641e71c52db5a6e2154d
testing.app.lifetime=60000

spring.jpa.open-in-view=false

logging.level.org.springframework.security=TRACE

spring.mail.host=smtp.yandex.ru
spring.mail.port=587
spring.mail.username=abtserenov@edu.hse.ru
spring.mail.password=giwwhbrsubudognu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
